export const pjtList = {
  items: [
    {
      image: "./assets/images/projects/pjt1.jpg",
      title: "MBR 432 villas, Dubai",
      sector: "Residential",
      link: "#",
      sqft: "1,60,5740",
      country: "UAE",
      status: "Ongoing",
      service: "Service2",
    },
    {
      image: "./assets/images/projects/pjt2.jpg",
      title: "MBR 398 villas, Dubai",
      sector: "Residential",
      link: "#",
      sqft: "1,50,0000",
      country: "UAE",
      status: "Ongoing",
      service: "Service2",
    },
    {
      image: "./assets/images/projects/pjt3.jpg",
      title: "Townhouse villas at Damac Lagoons",
      sector: "Residential",
      link: "#",
      sqft: "2,067,095",
      country: "UAE",
      status: "Ongoing",
      service: "Service2",
    },
    {
      image: "./assets/images/projects/pjt4.jpg",
      title: "Aura Gardens",
      sector: "Residential",
      link: "#",
      sqft: "22,138,50",
      country: "UAE",
      status: "Ongoing",
      service: "Service2",
    },
    {
      image: "./assets/images/projects/pjt5.jpg",
      title: "Imperial Avenue",
      sector: "Residential",
      link: "#",
      sqft: "1,45,1713",
      country: "UAE",
      status: "Ongoing",
      service: "Service2",
    },
    {
      image: "./assets/images/projects/pjt6.jpg",
      title: "Park Towers, Dubai",
      sector: "Residential",
      link: "#",
      sqft: "1,722,080",
      country: "UAE",
      status: "Completed",
      service: "Service1",
    },
    {
      image: "./assets/images/projects/pjt7.jpg",
      title: "Bloom Central (Hotel Marriott – Abu Dhabi)",
      sector: "Residential",
      link: "#",
      sqft: "1,122,505",
      country: "UAE",
      status: "Completed",
      service: "Service1",
    },
    {
      image: "./assets/images/projects/pjt8.jpg",
      title: "Cayan Cantara, Dubai",
      sector: "Residential",
      link: "#",
      sqft: "1,476,614",
      country: "UAE",
      status: "Completed",
      service: "Service1",
    },
    {
      image: "./assets/images/projects/pjt9.jpg",
      title: "Mudon villas and town houses",
      sector: "Residential",
      link: "#",
      sqft: "1,751,427 (P1) & 1,128,573 (P2)",
      country: "UAE",
      status: "Completed",
      service: "Service1",
    },
    {
      image: "./assets/images/projects/pjt10.jpg",
      title: "Design & build of 80 villas for phase 2C",
      sector: "Residential",
      link: "#",
      sqft: "322,917",
      country: "Oman",
      status: "Ongoing",
      service: "Service1",
    },
  ],
};


export const projectDetails = {
  list:[
    {
      title:"Iconic Projects",
      value:"2500+",
    },
    {
      title:"Diverse Sectors",
      value:"10+",
    }, 
  ] 

}