import mongoose from "mongoose";

const facadeSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaTitle_ar:{
        type:String,
    },
    metaDescription:{
        type:String,
        required:true
    },
    metaDescription_ar:{
        type:String,
    },
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    bannerAlt_ar:{
        type:String,
    },
    pageTitle:{
        type:String,
        required:true
    },
    pageTitle_ar:{
        type:String,
    },
    title:{
        type:String,
        required:true
    },
    title_ar:{
        type:String,
    },
    description:{
        type:String,
        required:true
    },
    description_ar:{
        type:String,
    },
    homeImage:{
        type:String
    },
    homeImageAlt:{
        type:String
    },
    homeImageAlt_ar:{
        type:String
    },
    link:{
        type:String
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        video:{
            type:String,
            required:true
        },
        poster:{
            type:String,
            required:true
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String
        },
        imageAlt_ar:{
            type:String
        },
    }
})

export default mongoose.models.Facade || mongoose.model("Facade", facadeSchema);