import mongoose from "mongoose";

const interiorDesignSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaTitle_ar:{
        type:String,
    },
    metaDescription:{
        type:String,
        required:true
    },
    metaDescription_ar:{
        type:String,
    },
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    bannerAlt_ar:{
        type:String,
    },
    pageTitle:{
        type:String,
        required:true
    },
    pageTitle_ar:{
        type:String,
    },
    title:{
        type:String,
        required:true
    },
    title_ar:{
        type:String,
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        video:{
            type:String,
            required:true
        },
        poster:{
            type:String,
            required:true
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
    fifthSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[
            {
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                },
                description:{
                    type:String,
                    required:true
                },
                description_ar:{
                    type:String,
                }
            }
        ]
    },
})

export default mongoose.models.InteriorDesign || mongoose.model("InteriorDesign", interiorDesignSchema);