import mongoose from "mongoose";

const mepSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaTitle_ar:{
        type:String,
    },
    metaDescription:{
        type:String,
        required:true
    },
    metaDescription_ar:{
        type:String,
    },
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    bannerAlt_ar:{
        type:String,
    },
    pageTitle:{
        type:String,
        required:true
    },
    pageTitle_ar:{
        type:String,
    },
    title:{
        type:String,
        required:true
    },
    title_ar:{
        type:String,
    },
    description:{
        type:String,
        required:true
    },
    description_ar:{
        type:String,
    },
    homeImage:{
        type:String
    },
    homeImageAlt:{
        type:String
    },
    homeImageAlt_ar:{
        type:String
    },
    link:{
        type:String
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        description:{
            type:String,
            required:true
        },
        description_ar:{
            type:String,
        },
        video:{
            type:String,
            required:true
        },
        poster:{
            type:String,
        },
        headProfilePic:{
            type:String,
        },
        headProfilePicAlt:{
            type:String,
        },
        headProfilePicAlt_ar:{
            type:String,
        },
        headName:{
            type:String,
        },
        headName_ar:{
            type:String,
        },
        headDesignation:{
            type:String,
        },
        headDesignation_ar:{
            type:String,
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[
            {
                image:{
                    type:String,
                    required:true
                },
                imageAlt:{
                    type:String
                },
                imageAlt_ar:{
                    type:String
                },
                title:{
                    type:String,
                    required:true
                },
                title_ar:{
                    type:String
                }
            }
        ]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[{
            title:{
                type:String,
            },
            title_ar:{
                type:String,
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String
            },
            imageAlt_ar:{
                type:String
            }
        }]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            imageAlt_ar:{
                type:String,
            },
            logo:{
                type:String,
            },
            logoAlt:{
                type:String,
            },
            logoAlt_ar:{
                type:String,
            },
            title:{
                type:String,
            },
            title_ar:{
                type:String,
            }, 
            description:{
                type:String
            },
            description_ar:{
                type:String
            }
        }],
    },
    fifthSection:{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            imageAlt_ar:{
                type:String,
            },
            title:{
                type:String,
            },
            title_ar:{
                type:String,
            }, 
            description:{
                type:String,
            },
            description_ar:{
                type:String,
            },  
        }],
    }
})

export default mongoose.models.Mep || mongoose.model("Mep", mepSchema);