import mongoose from "mongoose";

const newsSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
    },
    metaTitle_ar:{
        type:String
    },
    metaDescription:{
        type:String,
    },
    metaDescription_ar:{
        type:String,
    },
    title:{
        type:String,
        required:true
    },
    title_ar:{
        type:String
    },
    news:[{
        title:{
            type:String,
            required:true
        },
        title_ar:{
            type:String
        },
        coverImage:{
            type:String,
            required:true
        },
        coverImageAlt:{
            type:String,
        },
        coverImageAlt_ar:{
            type:String,
        },
        topic:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Topic",
            required:true
        },
        content:{
            type:String,
            required:true
        },
        content_ar:{
            type:String
        },
        slug:{
            type:String,
            required:true
        },
        thumbnail:{
            type:String,
            required:true
        },
        thumbnailAlt:{
            type:String,
        },
        thumbnailAlt_ar:{
            type:String,
        },
        metaTitle:{
            type:String,
        },
        metaTitle_ar:{
            type:String,
        },
        metaDescription:{
            type:String,
        },
        metaDescription_ar:{
            type:String,
        },
    }]
})

export default mongoose.models.News || mongoose.model("News", newsSchema);